spring:
  datasource:
    url: jdbc:mysql://localhost:3306/directory_generator?serverTimezone=Asia/Seoul&useUnicode=yes&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: password
    hikari:
      leak-detection-threshold: 1000
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: create-drop
    database: mysql


server:
  port: 8088
